updateCommitStatus: &UPDATE_COMMIT_STATUS update_commit_status eclipseReleaseGit --context "$step_name"

pipelines:
  - name: release_eclipse
    configuration:
      runtime:
        type: image
        image:
          auto:
            language: java
            versions:
              - "8.0.0"
      environmentVariables:
        readOnly:
          NEXT_VERSION: 0.0.0
          NEXT_DEVELOPMENT_VERSION: 0.0.0-SNAPSHOT

    steps:
      - name: Release
        type: Bash
        configuration:
          inputResources:
            - name: eclipseReleaseGit
          integrations:
            - name: github_generic
        execution:
          onStart:
            - *UPDATE_COMMIT_STATUS
            - restore_cache_files m2_home ${HOME}/.m2
          onExecute:
            - cd $res_eclipseReleaseGit_resourcePath

            # Configure git
            - git checkout master
            - git remote set-url origin https://$int_github_generic_token@github.com/jfrog/jfrog-eclipse-plugin.git

            # Make sure versions provided
            - echo "Checking variables"
            - test -n "$NEXT_VERSION" -a "$NEXT_VERSION" != "0.0.0"
            - test -n "$NEXT_DEVELOPMENT_VERSION" -a "$NEXT_DEVELOPMENT_VERSION" != "0.0.0-SNAPSHOT"

            # Update version - tycho-versions-plugin:1.7.0 is the max version supported by Java 8
            - env -i PATH=$PATH M2_HOME=$M2_HOME HOME=$HOME mvn org.eclipse.tycho:tycho-versions-plugin:1.7.0:set-version -DnewVersion=$NEXT_VERSION -B
            - git commit -am "[artifactory-release] Release version ${NEXT_VERSION} [skipRun]" --allow-empty
            - git tag ${NEXT_VERSION}
            - git push
            - git push --tags

            # Update next development version
            - env -i PATH=$PATH M2_HOME=$M2_HOME HOME=$HOME mvn org.eclipse.tycho:tycho-versions-plugin:1.7.0:set-version -DnewVersion=$NEXT_DEVELOPMENT_VERSION -B
            - git commit -am "[artifactory-release] Next development version [skipRun]"
            - git push

          onComplete:
            # Show tests in the *Tests* tab
            - save_tests $res_eclipseReleaseGit_resourcePath/tests/target/surefire-reports/

            - *UPDATE_COMMIT_STATUS

            # Save .m2 cache
            - add_cache_files ${HOME}/.m2 m2_home
